#!/usr/bin/env bash
# generate_secrets.sh
#
# SECURITY NOTE (P0 audit fix):
#   This script never embeds privileged credentials into the compiled binary.
#   It does embed public client configuration: the Supabase URL and publishable
#   key (or the legacy low-privilege anon key), plus the Sentry ingestion DSN.
#   Mobile clients necessarily expose these identifiers; RLS/user JWTs and the
#   Sentry management API remain the privileged authorization boundaries.
#
# What this script does now:
#   1. Always emits GeneratedSecrets.swift so the project compiles on a fresh
#      checkout. Public client configuration is read from .env when present;
#      privileged credentials remain empty and are resolved from Keychain.
#   2. When a project-root .env file IS present, it additionally writes a
#      `.secrets.local` reference file (gitignored) so developers can see the
#      values that were configured, AND prints the
#      `security add-generic-password` commands they can run to seed those
#      values into a macOS keychain entry.
#
# Xcode Run Script Phase (before Compile Sources):
#   "${SRCROOT}/scripts/generate_secrets.sh"
#
# Input  (optional): ${SRCROOT}/.env
# Output (always):   ${SRCROOT}/DayPage/Config/GeneratedSecrets.swift
# Output (if .env):  ${SRCROOT}/.secrets.local  (developer reference, gitignored)

set -euo pipefail

# Allow invocation outside of Xcode by defaulting SRCROOT to repo root.
SRCROOT="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

ENV_FILE="${SRCROOT}/.env"
OUTPUT_FILE="${SRCROOT}/DayPage/Config/GeneratedSecrets.swift"
LOCAL_REFERENCE_FILE="${SRCROOT}/.secrets.local"

# ── Helper: read a value from .env without leaking it into logs ──────────────
read_env_value() {
    local key="$1"
    local value=""
    if [[ -f "${ENV_FILE}" ]]; then
        value=$(awk -v key="${key}" '
            index($0, key "=") == 1 {
                value = substr($0, length(key) + 2)
                sub(/\r$/, "", value)
                print value
                exit
            }
        ' "${ENV_FILE}")
    fi
    printf '%s' "${value}"
}

# ── 1. Emit GeneratedSecrets.swift ──────────────────────────────────────────
# Public client configuration is safe and necessary to embed. Privileged API
# credentials and management tokens stay empty and must be supplied via Keychain.
mkdir -p "$(dirname "${OUTPUT_FILE}")"

# Escape backslash and double-quote for Swift string literal embedding.
escape_swift() {
    local v="$1"
    v="${v//\\/\\\\}"
    v="${v//\"/\\\"}"
    printf '%s' "$v"
}
DEEPSEEK_BASE_URL_PUBLIC=$(escape_swift "$(read_env_value DEEPSEEK_BASE_URL)")
DEEPSEEK_MODEL_PUBLIC=$(escape_swift "$(read_env_value DEEPSEEK_MODEL)")
SUPABASE_URL_PUBLIC=$(escape_swift "$(read_env_value SUPABASE_URL)")
supabase_publishable_key_value=$(read_env_value SUPABASE_PUBLISHABLE_KEY)
if [[ -z "${supabase_publishable_key_value}" ]]; then
    # Backward compatibility for existing GitHub ENV_FILE/local .env values.
    # The legacy anon JWT has the same low-privilege client role as the newer
    # sb_publishable_ key and is intentionally bundled in public clients.
    supabase_publishable_key_value=$(read_env_value SUPABASE_ANON_KEY)
fi
SUPABASE_PUBLISHABLE_KEY_PUBLIC=$(escape_swift "${supabase_publishable_key_value}")
SENTRY_DSN_PUBLIC=$(escape_swift "$(read_env_value SENTRY_DSN)")
VOICE_ASR_PROVIDER_PUBLIC=$(escape_swift "$(read_env_value VOICE_ASR_PROVIDER)")
DOUBAO_ASR_STREAM_URL_PUBLIC=$(escape_swift "$(read_env_value DOUBAO_ASR_STREAM_URL)")
DOUBAO_ASR_FILE_URL_PUBLIC=$(escape_swift "$(read_env_value DOUBAO_ASR_FILE_URL)")

cat > "${OUTPUT_FILE}" << SWIFT
// GeneratedSecrets.swift — AUTO-GENERATED by scripts/generate_secrets.sh
// DO NOT EDIT MANUALLY. DO NOT COMMIT (see .gitignore).
//
// PRIVILEGED CREDENTIALS (DeepSeek, Whisper, weather, GitHub, and speech-
// provider credentials) are intentionally LEFT EMPTY here. They MUST
// be provided at runtime via the iOS Keychain (see SecretsRuntime.swift).
// Embedding secrets at compile time would leak them into every IPA archive
// — see the P0 security audit for context.
//
// Public client configuration (including Supabase's publishable/legacy anon
// key and Sentry's ingestion DSN) is intentionally embedded. Mobile clients
// cannot keep these values secret; never substitute service/admin credentials.

enum Secrets {
    // ── Secrets (always empty in source; resolved from Keychain at runtime)
    static let deepSeekApiKey: String = ""
    static let openAIWhisperApiKey: String = ""
    static let openWeatherApiKey: String = ""
    static let kubotGitHubToken: String = ""
    // Doubao ASR: appID pairs with accessToken to authenticate every request,
    // so it is treated as a credential (Keychain) rather than embedded config.
    static let doubaoASRAppID: String = ""
    static let doubaoASRAccessToken: String = ""
    static let doubaoASRSecretKey: String = ""

    // ── Non-secret configuration (safe to embed)
    static let deepSeekBaseURL: String = "${DEEPSEEK_BASE_URL_PUBLIC}"
    static let deepSeekModel: String = "${DEEPSEEK_MODEL_PUBLIC}"
    static let supabaseURL: String = "${SUPABASE_URL_PUBLIC}"
    static let supabasePublishableKey: String = "${SUPABASE_PUBLISHABLE_KEY_PUBLIC}"
    static let sentryDSN: String = "${SENTRY_DSN_PUBLIC}"
    static let voiceASRProvider: String = "${VOICE_ASR_PROVIDER_PUBLIC}"
    static let doubaoASRStreamURL: String = "${DOUBAO_ASR_STREAM_URL_PUBLIC}"
    static let doubaoASRFileURL: String = "${DOUBAO_ASR_FILE_URL_PUBLIC}"
}
SWIFT

echo "[generate_secrets] wrote ${OUTPUT_FILE} (privileged credentials blank; public client config embedded when present)"

# ── 2. If .env exists, emit developer-only reference + Keychain hints ────────
if [[ ! -f "${ENV_FILE}" ]]; then
    echo "[generate_secrets] no ${ENV_FILE} found — skipping .secrets.local reference."
    echo "[generate_secrets] supply API keys at runtime through Settings → Onboarding (Keychain)."
    exit 0
fi

DEEPSEEK_API_KEY=$(read_env_value "DEEPSEEK_API_KEY")
DEEPSEEK_BASE_URL=$(read_env_value "DEEPSEEK_BASE_URL")
DEEPSEEK_MODEL=$(read_env_value "DEEPSEEK_MODEL")
OPENAI_WHISPER_API_KEY=$(read_env_value "OPENAI_WHISPER_API_KEY")
VOICE_ASR_PROVIDER=$(read_env_value "VOICE_ASR_PROVIDER")
DOUBAO_ASR_APP_ID=$(read_env_value "DOUBAO_ASR_APP_ID")
DOUBAO_ASR_ACCESS_TOKEN=$(read_env_value "DOUBAO_ASR_ACCESS_TOKEN")
DOUBAO_ASR_SECRET_KEY=$(read_env_value "DOUBAO_ASR_SECRET_KEY")
OPENWEATHER_API_KEY=$(read_env_value "OPENWEATHER_API_KEY")
SUPABASE_URL=$(read_env_value "SUPABASE_URL")
SUPABASE_PUBLISHABLE_KEY=$(read_env_value "SUPABASE_PUBLISHABLE_KEY")
SUPABASE_ANON_KEY=$(read_env_value "SUPABASE_ANON_KEY")
SENTRY_DSN=$(read_env_value "SENTRY_DSN")
KUBOT_GITHUB_TOKEN=$(read_env_value "KUBOT_GITHUB_TOKEN")

umask 077
cat > "${LOCAL_REFERENCE_FILE}" << REF
# .secrets.local — developer reference, DO NOT COMMIT.
# Mirrors the values read from .env at build time. The app does NOT read
# this file — it is only here so you can copy/paste values into the in-app
# onboarding flow or the keychain commands printed below.
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
OPENAI_WHISPER_API_KEY=${OPENAI_WHISPER_API_KEY}
VOICE_ASR_PROVIDER=${VOICE_ASR_PROVIDER}
DOUBAO_ASR_APP_ID=${DOUBAO_ASR_APP_ID}
DOUBAO_ASR_ACCESS_TOKEN=${DOUBAO_ASR_ACCESS_TOKEN}
DOUBAO_ASR_SECRET_KEY=${DOUBAO_ASR_SECRET_KEY}
OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SENTRY_DSN=${SENTRY_DSN}
KUBOT_GITHUB_TOKEN=${KUBOT_GITHUB_TOKEN}
REF
echo "[generate_secrets] wrote developer reference ${LOCAL_REFERENCE_FILE} (0600)"

# Suggested manual Keychain seed commands. We deliberately do NOT execute
# these automatically — the iOS app's KeychainHelper writes into the app's
# own keychain service (which lives inside the Simulator/device sandbox),
# and we don't want to silently touch the user's login keychain.
cat <<HINT
[generate_secrets] To seed the iOS Simulator keychain, run the app once and
[generate_secrets] paste each value in Settings → API Keys.
[generate_secrets]
[generate_secrets] For ad-hoc macOS keychain storage you can use, e.g.:
[generate_secrets]   security add-generic-password -U -s com.daypage.apikeys -a deepSeekApiKey -w '<value>'
[generate_secrets]   security add-generic-password -U -s com.daypage.apikeys -a openAIWhisperApiKey -w '<value>'
[generate_secrets]   security add-generic-password -U -s com.daypage.apikeys -a openWeatherApiKey -w '<value>'
[generate_secrets]   security add-generic-password -U -s com.daypage.apikeys -a doubaoASRAppID -w '<value>'
[generate_secrets]   security add-generic-password -U -s com.daypage.apikeys -a doubaoASRAccessToken -w '<value>'
[generate_secrets]   security add-generic-password -U -s com.daypage.apikeys -a doubaoASRSecretKey -w '<value>'
[generate_secrets] (Replace <value> with the corresponding entry from .secrets.local.)
HINT
