name: Project Automation

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions: {}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        if: ${{ env.PROJECT_TOKEN != '' }}
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        with:
          project-url: https://github.com/orgs/getyak/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}
